session_name: whistle
windows:
    - window_name: source
      panes:
        - source wi_venv/bin/activate && vim -o TODO.md README.md
    - window_name: test
      panes:
        - source wi_venv/bin/activate

